services:
  - type: web
    name: classiface-hardened
    runtime: python
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && pip install --no-deps face_recognition==1.3.0
    startCommand: gunicorn --worker-class gthread -w 1 --threads 8 --timeout 180 --limit-request-line 8190 --limit-request-field_size 32768 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_DATABASE_URL
        value: https://classiface-1a8ca-default-rtdb.asia-southeast1.firebasedatabase.app/
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: EMBED_KEY
        sync: false
      - key: FLASK_SECRET
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
