services:
  - type: web
    name: classiface-hardened
    runtime: python
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --limit-request-line 8190 --limit-request-field_size 32768 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_DATABASE_URL
        value: https://classiface-1a8ca-default-rtdb.asia-southeast1.firebasedatabase.app/
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: EMBED_KEY
        sync: false
      - key: FLASK_SECRET
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
